version: "3.8"

services:
    api:
        build: .
        ports:
            - "8080:8080"
        env_file:
            - .env
        volumes:
            - ./data:/app/data
        environment:
            - GIN_MODE=release
